### ISSUE TITLE
Our drawLine function destroys previous line width/cap state

### ISSUE THREAD

**Issue by rjbailey** [rjbailey/canvas-whispers#7]
The [`drawLine` function](https://github.com/rjbailey/canvas-whispers/blob/master/canvaswhispers.js#L66-L78) currently saves and restores the previous value for the stroke color, but destructively sets the line width and line endcaps.

We could write both `drawLine` and `drawPoint` in a more robust way by [saving and restoring all of the canvas' state](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Transformations#Saving_and_restoring_state) instead of just saving and restoring the color.

**Comment by sidereus7** [comment]
We decided to store all canvas state in the canvas. Since we will never change color either, this seemed like not a thing we wanted to do.
